# Generated by Django 4.2.1 on 2023-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='course_directions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='courses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='graduates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='main_subtitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='main_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
