# Generated by Django 4.2.1 on 2023-05-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=50)),
                ('director_img', models.ImageField(upload_to='')),
                ('biz_haqimizda', models.TextField()),
                ('faoliyatimiz', models.TextField()),
                ('dfaoliyat_img', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
    ]
