# Generated by Django 4.2.1 on 2023-05-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='product/')),
                ('product_image_2', models.ImageField(upload_to='product/')),
                ('product_url_web', models.CharField(blank=True, max_length=250, null=True)),
                ('product_url_ios', models.CharField(blank=True, max_length=250, null=True)),
                ('product_url_android', models.CharField(blank=True, max_length=250, null=True)),
                ('spend_time', models.IntegerField()),
                ('users', models.IntegerField()),
                ('mijoz_haqida', models.TextField(blank=True, null=True)),
                ('talablar', models.TextField(blank=True, null=True)),
                ('topshirilgan_sana', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
