# Generated by Django 4.2.1 on 2023-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutus_course_directions_aboutus_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='product_name',
            field=models.CharField(max_length=350),
        ),
    ]
