# Generated by Django 4.2.1 on 2023-12-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_projects_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='queue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Navbati'),
        ),
    ]
