# Generated by Django 4.2.1 on 2023-05-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='address',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AlterField(
            model_name='projects',
            name='topshirilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
