# Generated by Django 4.2.1 on 2023-05-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_about_address_remove_about_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
