# Generated by Django 4.2.1 on 2023-06-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='mijoz_haqida',
            new_name='about_customer',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='topshirilgan_sana',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='talablar',
            new_name='requirements',
        ),
        migrations.AddField(
            model_name='mentors',
            name='image',
            field=models.ImageField(default=1, upload_to='mentors/'),
            preserve_default=False,
        ),
    ]
