# Generated by Django 4.2.1 on 2023-06-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_rename_mijoz_haqida_projects_about_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('director', models.CharField(blank=True, max_length=70, null=True)),
                ('director_pos', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
